service: seedata
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
          - ses:*
      Resource: '*'

functions:
  googleLookupEmail:
    handler: lambdas/scheduleTasks/googleLookupEmail.handler

    events:
      - schedule: rate(1 hour)
    environment:
      GOOGLE_SEARCH_API_URL: ${file(./config.yml):GOOGLE_SEARCH_API_URL}
      GOOGLE_SEARCH_API_KEY: ${file(./config.yml):GOOGLE_SEARCH_API_KEY}
      GOOGLE_ENGINE_ID: ${file(./config.yml):GOOGLE_ENGINE_ID}


